// Public, anonymized technology references. Do not add employers or employment dates.
export const experienceTechnologies: Record<string, string[]> = {
  enterprise: [
    "React",
    "TypeScript",
    "Material UI",
    "RTK Query",
    "Node.js",
    "Azure Functions",
    "SQL Server",
    "Redis",
  ],
  serverless: [
    "TypeScript",
    "Node.js",
    "AWS Lambda",
    "AppSync",
    "GraphQL",
    "DynamoDB",
    "AWS CDK",
    "Serverless Framework",
  ],
  marketplace: [
    "Next.js",
    "React",
    "Node.js",
    "Express.js",
    "MongoDB",
    "OpenAI API",
    "Vercel",
    "Railway",
  ],
  commerce: ["Magento Enterprise", "JavaScript", "HTML", "CSS"],
  hospitality: ["React", "Material UI", "Stripe", "i18n", "Heroku"],
};
export const coreTechnologies = [
  "React",
  "Next.js",
  "TypeScript",
  "Material UI",
  "Node.js",
  "REST",
  "GraphQL",
  "AWS",
  "Azure",
  "DynamoDB",
  "MongoDB",
  "SQL Server",
  "Redis",
  "GitHub Actions",
  "GitLab CI/CD",
  "Jest",
  "Contentful",
  "Strapi",
];
