export const technologyIcons: Record<string, string> = {
  React: "react",
  "Next.js": "nextjs",
  TypeScript: "typescript",
  "Material UI": "mui",
  "Node.js": "nodejs",
  GraphQL: "graphql",
  AWS: "aws",
  Azure: "azure",
  DynamoDB: "dynamodb",
  MongoDB: "mongodb",
  "SQL Server": "sqlserver",
  Redis: "redis",
  "GitHub Actions": "githubactions",
  "GitLab CI/CD": "gitlab",
  Jest: "jest",
  Contentful: "contentful",
  Strapi: "strapi",
};
